version: "3"

services:

  httpd:
    build:
      context: ./httpd
    container_name: "httpd-server"
    ports:
      - "6666:80"
      - "8443:443"
    depends_on:
      - php
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./php
    container_name: "php-engine"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    restart: on-failure
    ports:
      - "9000:9000"
    volumes:
      - ./www:/usr/local/apache2/htdocs/
    networks:
      - backend

  db3:
    container_name: db3
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9906:3306"
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db3
    depends_on:
      - db3
    networks:
      - backend
networks:
  frontend:
  backend:
